# Hiya! Qclid here. So obviously, port is the port the server runs on,
# and index-file is the file that gets served when you access the root URL.
# Make sure the port you choose is open and not blocked by a firewall. You probably don't have to worry about this cause a normal hosting service will handle it for you.
# Just make sure you use a port thats not the port the minecraft server is using (default 25565).
# Also, make sure the index-file you choose actually exists in the web/ folder, otherwise you'll get a 404 error when accessing the root URL.

# Have fun!
port: 8080
websocket-port: 8081
index-file: index.html

rate-limiting:
  enabled: true
  delay: 1000 # The delay in milliseconds between requests from the same IP address

# Whitelist/Blacklist configuration
# If is_whitelist_on is true, only IPs in the ip_list will be allowed.
# If is_whitelist_on is false, IPs in the ip_list will be blocked.
is_whitelist_on: false
ip_list: []

logging:
  # Enable console logging, default is false
  console: false
  # Enable IP logging to a file, default is true
  ip: true
