# Hiya! Qclid here. So obviously, port is the port the server runs on,
# and index-file is the file that gets served when you access the root URL.
# Make sure the port you choose is open and not blocked by a firewall. You probably don't have to worry about this cause a normal hosting service will handle it for you.
# Just make sure you use a port thats not the port the minecraft server is using (default 25565).
# Also, make sure the index-file you choose actually exists in the web/ folder, otherwise you'll get a 404 error when accessing the root URL.


# Have fun!
port: 8080
index-file: index.html
